---
dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
install:
  - pip install pytest pytest-cov
script:
  - pytest --cov
  - python setup.py install
after_success: bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - name: omnilint
      language: generic
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
      after_success:
    - stage: deploy
      install: true
      script: true
      python: 3.7
      deploy:
        provider: pypi
        user: lpenz
        password:
          secure: cIYfZyYIFyavK6FHd8kj1vRGQSoEEnhVEgbkXGCs/SHAgNzezAu/idhUeu1E3T2mW/LBrldEVXE9tQYsOlmWBg1t1W+sWNgWRcURBDA6vh2/GJOI54B7BMVBaShXRtKNAhdujYMdRUG7DC/RRGOCFtnxLtnzseK1ND+kqqKGJ0Y=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: lpenz/watchng
