script:
 - sed -n 's@PROGRAM_VERSION = .\([0-9.]\+\).$@watchng_\1@p' watchng > /tmp/v
 - cat /tmp/v
 - git archive --prefix=$(cat /tmp/v)/ --format=tar -o ../$(cat /tmp/v).orig.tar HEAD
 - gzip ../$(cat /tmp/v).orig.tar
 - dpkg-buildpackage -uc -us -sa
 - lintian -c -i ../*.changes
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq txt2tags lintian

