script:
 - git archive --prefix=watchng_1.1/ --format=tar -o ../watchng_1.1.orig.tar HEAD
 - gzip ../watchng_1.1.orig.tar
 - dpkg-buildpackage -uc -us
 - lintian
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq txt2tags lintian

