---
sudo: required # docker
services: [docker]
language: generic
script:
  - docker pull debian:stretch
  - docker run -d --name debian -v "$PWD/..":/home debian:stretch sleep 9999999999
  - docker exec -t debian /bin/bash -c "apt-get update && apt-get install -y --no-install-recommends git-buildpackage fakeroot gcc build-essential debhelper txt2tags"
  - docker exec -t debian /bin/bash -c "cd /home/watchng && gbp buildpackage --git-ignore-branch -us -uc"
  - docker rm -f debian
  - sudo chown -R "$USER:$USER" ../
  - ls -l ..
deploy:
  provider: packagecloud
  repository: lpenz
  username: lpenz
  token:
    secure: nWcA7d/gUnRBl8UFvzFTPygHKBnkmNgAGOsvekm0nLK/Sgp+jMRi6CHtDtB3oRu6hYirLBomC8LVrC6rY27x6gbTfEw7m2qUV+IqmcabBW8UxlU8G9HiwqevcG3vOaundBOvWLtMloNgtct1AzfiWTsDNgYuEVsXimjlgeqBM7o=
  dist: debian/stretch
  local-dir: ".."
  package_glob: "*.deb"
  on:
    branch: debian-debian
    tags: true
