#!/bin/bash

DEBIAN_REVISION=${INPUT_DEBIAN_REVISION:-0}

set -e -x

python3 setup.py --command-packages=stdeb.command \
        sdist_dsc --debian-version "$DEBIAN_REVISION" \
        bdist_deb
cp -l ./deb_dist/*.deb .
